# Site settings
title: 'caffeinatedmoo.se' # Your Title
tagline: 'well-crafted code and other moose topics' # A brief tagline for your site
permalink: none

# Build settings
markdown: redcarpet
highlighter: pygments
